WIP -- added placeholder file for the nearPD function
scalanlp/breeze pull request #800
Opened 2021-02-01 10:27 UTC by ewalsh

Adding a function to find the nearest positive definite matrix via the Higham (2002) algorithm.

2021-02-14 06:26 UTC, dlwh requested changes
sorry for being slow here, and thank you for submitting it. I have a bunch of comments about style, and I'd really like to see a few unit tests, since I really have no idea if this algorithm is correct.

2021-02-14 06:26 UTC, dlwh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +class NearPD(matA: DenseMatrix[Double], corrBool: Boolean = false, keepDiag: Boolean = false,
Is there a reason this needs to be a class? AFAICT you're only doing it to make it top level? Could you maybe put it in the linalg package object as a def? or make it an object with an apply method?

2021-02-14 06:26 UTC, dlwh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +class NearPD(matA: DenseMatrix[Double], corrBool: Boolean = false, keepDiag: Boolean = false,
(I don't think there's a reason to make this a "UFunc" fwiw)

2021-02-14 06:26 UTC, dlwh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +  * @param doDykstra Boolean indicating if Dykstra's correction should be used;
i'd prefer there be an `algo: NearPD.Algorithm` or something, where NearPD.Algorithm is a sealed trait or an enum

2021-02-14 06:26 UTC, dlwh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +    val matX = chooseAlgo(symA, doDykstra)
I don't like this. how about inlining?

`val matX = if(algo == Dystrka) doDystrkaFunc( ) else doDirect()`

2021-02-14 06:26 UTC, dlwh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +  def keepDiagFunc(mat: DenseMatrix[Double], bool: Boolean): DenseMatrix[Double] = {
as with chooseAlgo i'd rather you just inline the boolean gating of this method and this method only does the keepDiag part

2021-02-14 06:26 UTC, dlwh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +  def doSymFunc(mat: DenseMatrix[Double], bool: Boolean): DenseMatrix[Double] = {
same

2021-02-14 06:26 UTC, dlwh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +  def corrDiagFunc(mat: DenseMatrix[Double], bool: Boolean): DenseMatrix[Double] = {
same

2021-02-14 06:26 UTC, dlwh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +        DenseMatrix.tabulate(mat.rows, mat.cols)({
i might be misremembering, but I think this would be simpler/quicker as

```
val corrDiaged = mat.copy
diag(corrDiaged) := 1.0
corrDiaged
```

2021-02-14 06:26 UTC, dlwh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +  * @param convNormType convergence norm type (norm(*, type)) used for Higham
I'd rather a sealed trait here

2021-02-14 06:26 UTC, dlwh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +        println(s"iter ${iter} : p = ${breeze.linalg.sum(vecd)} ||Y-X|| / ||Y|| = ${conv}")
i prefer to use logging rather than printlns in breeze

2021-02-14 06:26 UTC, dlwh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +      val pcheck = breeze.linalg.sum(p.map(x => bool2Dbl(x)))
val pcheck = any(vecd > eigTol)

2021-02-14 06:26 UTC, dlwh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +        break
you have to wrap the loop you're breaking out of in breakable in Scala. It's dumb

2021-02-14 06:26 UTC, dlwh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +  def doDirectFixedPt(mat: DenseMatrix[Double]): DenseMatrix[Double] = {
this function shares a ton of code with the one above. Is it possible to extra out more. I know I had you inline some stuff, but I think it would be cleaner to extract out the pcheck stuff, and the eigVecVals etc stuff, or possibly to make it so that the main loop takes a function as input that does the differences between the two algorithms, though I think that might be worse.

2021-02-14 06:26 UTC, dlwh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +// val matA = DenseMatrix(Array(Array(1,     0.477, 0.644, 0.478, 0.651, 0.826),
it would be good to make this into a test, and maybe add some randomized tests about properties this function should have, e.g.: for any matrix you give it (that one might want to give it), the output is a PD matrix or it errors, and it doesn't error too much, or something like that.

2021-02-14 06:26 UTC, dlwh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +  def bool2Dbl(bool: Boolean): Double = {
i don't think you actually need this here, but if you do, there's a function in breeze called `I` for indicator function that does exactly this, except it works on vectors

2021-02-14 18:42 UTC, ewalsh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +class NearPD(matA: DenseMatrix[Double], corrBool: Boolean = false, keepDiag: Boolean = false,
First, thank you for your comments. I found all of them very helpful, and they are very much appreciated. It may take me a hot minute but I will address everything ASAP.

2021-03-07 18:25 UTC, ewalsh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +class NearPD(matA: DenseMatrix[Double], corrBool: Boolean = false, keepDiag: Boolean = false,
I have addressed or commented on each of these points. Please feel free to add any other comments, I will defer to you to revolve each based on your approval.

I have changed to an object with an apply method

2021-03-07 18:26 UTC, ewalsh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +  * @param doDykstra Boolean indicating if Dykstra's correction should be used;
I have added sealed traits for both the algorithm and choice of convergence norm type. This makes more sense and I hope is easier to read.

2021-03-07 18:26 UTC, ewalsh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +    val matX = chooseAlgo(symA, doDykstra)
I have changed style to inline in each opportunity that I found

2021-03-07 18:26 UTC, ewalsh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +  def keepDiagFunc(mat: DenseMatrix[Double], bool: Boolean): DenseMatrix[Double] = {
done

2021-03-07 18:26 UTC, ewalsh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +  def doSymFunc(mat: DenseMatrix[Double], bool: Boolean): DenseMatrix[Double] = {
done

2021-03-07 18:27 UTC, ewalsh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +      val pcheck = breeze.linalg.sum(p.map(x => bool2Dbl(x)))
incorporated directly

2021-03-07 18:27 UTC, ewalsh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +        break
done

2021-03-07 18:30 UTC, ewalsh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +  def doDirectFixedPt(mat: DenseMatrix[Double]): DenseMatrix[Double] = {
This one is the only one I haven't truly addressed. The rationale is this, it would be possible to extract out a lot of the code here. However, when running the function it would require running an if statement within the loop to check which algorithm to run. 

Please advise. I'd be happy to change, but I just wanted to point out the original rationale. I think in large cases where lots of iterations are needed this repetitive checking could be slower than necessary.

2021-03-07 18:30 UTC, ewalsh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +// val matA = DenseMatrix(Array(Array(1,     0.477, 0.644, 0.478, 0.651, 0.826),
Done and I also added another simple test

2021-03-07 18:31 UTC, ewalsh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +  def bool2Dbl(bool: Boolean): Double = {
Agreed and removed

2021-04-07 18:01 UTC, dlwh reviewed
sorry for being so slow, just a few more comments

2021-04-07 18:01 UTC, dlwh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +      def normTypeFunc(matX: DenseMatrix[Double], matY: DenseMatrix[Double], normType: ConvergenceNormType): Double = {
i should really fix norm for matrices...

2021-04-07 18:01 UTC, dlwh commented on math/src/main/scala/breeze/linalg/functions/nearpd.scala
> +          println("Matrix seems negative semi-definite")
throw?

2025-09-19 16:31 UTC, closed without merging