single precision support added for LeastSquares calculation
scalanlp/breeze pull request #857
Opened 2023-12-30 14:31 UTC by dineshdharme

Hello David Hall,

This PR adds support for doing Least Squares calculation for Float datatype.
Please review this.
```

  def NaiveMultiplicationFloat(n: Int, flag: Boolean): Unit = {

    val N_Dim = 4
    val rows = N_Dim + 5
    val columns = N_Dim
    val randomDoubleArray = Array.fill(rows * columns) {math.random}.map(ele => ele.toFloat)
    val sm: DenseMatrix[Float] = DenseMatrix.create(rows, columns, randomDoubleArray)

    val features2DMatrix = sm(::, 1 to -1)
    val targetPPNRVector = sm(::, 0)
   println("sm" +  sm)
    val result = leastSquares(features2DMatrix, targetPPNRVector)
    println("Breeze Linear Equation Solver results")

    println(s"intercept = ${result.coefficients.toArray.slice(1 , 5).mkString("[", ",", "]")}")
   println(s"r^2 = ${result.rSquared}")

  }
```

This code should allow you to test the Float datatype.

2024-01-04 16:55 UTC, dlwh requested changes
Hi @dineshdharme thanks for submitting this!

So, typically in Breeze we aim for compile time errors rather than runtime errors. Here, we would get a runtime error if we tried to use it for Complex or something. so rather than the match, it would be better if there were two implementations of each of `matrixVector`, `matrixVectorSpecifiedWork` and `matrixVectorSpecifiedWork`

2024-01-04 16:57 UTC, dineshdharme commented
Thank you, I will update the PR tomorrow and let you know.

2024-01-05 18:39 UTC, dineshdharme commented
Hi David,

I made changes as you requested. Please take a look and let me know.

2024-01-07 23:08 UTC, dlwh reviewed
almost there, thank you

2024-01-07 23:08 UTC, dlwh commented on math/src/main/scala/breeze/stats/regression/LeastSquares.scala
> +    case _: NumericType[Float]  =>
let's make this method something like

```
def apply(x: DenseVector[T])(implicit can_dot: OpMulInner.Impl2[DenseVector[T], DenseVector[T], T]) = {
}
```

and then you can remove all of the switches and exception stuff.

2024-01-07 23:08 UTC, dlwh commented on math/src/main/scala/breeze/stats/regression/LeastSquares.scala
> +  def apply(X: DenseMatrix[T]): DenseVector[T] = ev match {
similarly 

let's make this method something like

```
def apply(x: DenseVector[T])(implicit can_dot: OpMulMatrix.Impl2[DenseMatrix[T], DenseVector[T], T]) = {
}
```

and then you can remove all of the switches and exception stuff.

2024-01-08 17:23 UTC, dineshdharme commented
I made the changes you requested. The only difference is for first apply I had to move the `implicit can_dot` to case class
as scala didn't recognize it to be `Function1`'s `apply` trait.  

Please review. thanks!

2024-01-13 06:09 UTC, dlwh approved these changes
thanks!

2024-01-13 07:42 UTC, merged